# Generated by Django 5.2.4 on 2025-09-02 09:59

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import src.apps.common.utils.files.images
import src.apps.common.utils.other
import src.apps.common.utils.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=200)),
                ('expire_date', models.DateTimeField(default=src.apps.common.utils.other.default_expire_date)),
            ],
            options={
                'verbose_name': 'Email Code',
                'verbose_name_plural': 'Email Codes',
                'db_table': 'CodeEmail',
            },
        ),
        migrations.CreateModel(
            name='DailyUserStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, unique=True)),
                ('total_users', models.PositiveIntegerField(default=0)),
                ('active_users', models.PositiveIntegerField(default=0)),
                ('inactive_users', models.PositiveIntegerField(default=0)),
                ('authorized_users', models.PositiveIntegerField(default=0)),
                ('not_authorized_users', models.PositiveIntegerField(default=0)),
                ('new_users_today', models.PositiveIntegerField(default=0)),
                ('deactivated_users_today', models.PositiveIntegerField(default=0)),
                ('complete_profile_users', models.PositiveIntegerField(default=0)),
                ('role_distribution', models.JSONField(default=dict)),
                ('total_enrollments', models.PositiveIntegerField(default=0)),
                ('active_enrollments', models.PositiveIntegerField(default=0)),
                ('email_verified_rate', models.FloatField(default=0.0)),
                ('profile_completion_rate', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Daily User Statistics',
                'verbose_name_plural': 'Daily User Statistics',
                'db_table': 'Daily User Statistics',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='TemporaryUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(blank=True, max_length=150, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('region', models.CharField(max_length=255)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('role', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=255)),
                ('re_password', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'TemporaryUser',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('google_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('email_verified', models.BooleanField(default=False)),
                ('must_set_password', models.BooleanField(default=True)),
                ('mfa_enabled', models.BooleanField(default=False)),
                ('role', models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher'), ('admin', 'Admin')], default='student', max_length=20)),
                ('is_deleted', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'Users',
            },
        ),
        migrations.CreateModel(
            name='CodePassword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('expire_date', models.DateTimeField(default=src.apps.common.utils.other.default_expire_date)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Password Code',
                'verbose_name_plural': 'Password Codes',
                'db_table': 'CodePassword',
            },
        ),
        migrations.CreateModel(
            name='EmailVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_email', models.EmailField(max_length=254)),
                ('code', models.CharField(max_length=10)),
                ('expire_date', models.DateTimeField(default=src.apps.common.utils.other.default_expire_date)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Email Verifications',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('middle_name', models.CharField(blank=True, max_length=120, null=True)),
                ('interface_language', models.CharField(blank=True, default='en', max_length=10, null=True)),
                ('timezone', models.CharField(blank=True, default='UTC+5', max_length=64, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('profile_edit_blocked', models.BooleanField(default=False)),
                ('deactivation_time', models.DateTimeField(blank=True, null=True)),
                ('days_to_delete', models.PositiveIntegerField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('company', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to=src.apps.common.utils.files.images.unique_image_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png']), src.apps.common.utils.validators.validate_image_size])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'db_table': 'Users Profile',
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_active', 'must_set_password', 'email_verified'], name='Users_is_acti_7318bb_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role', 'is_active'], name='Users_role_8c8944_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email', 'first_name', 'last_name'], name='Users_email_4e19c2_idx'),
        ),
        migrations.AddConstraint(
            model_name='userprofile',
            constraint=models.UniqueConstraint(condition=models.Q(('phone_number', None), _negated=True), fields=('phone_number',), name='unique_phone_number_when_set'),
        ),
    ]
