# Generated by Django 5.2.4 on 2025-09-15 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='days_to_delete',
            new_name='days_to_delete_after_deactivation',
        ),
    ]
