# Generated by Django 5.2.4 on 2025-09-04 12:35

import django.core.validators
import src.apps.common.utils.files.images
import src.apps.common.utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='video_url',
        ),
        migrations.AddField(
            model_name='task',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='task_files/'),
        ),
        migrations.AddField(
            model_name='task',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=src.apps.common.utils.files.images.unique_image_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png']), src.apps.common.utils.validators.validate_image_size]),
        ),
        migrations.AddField(
            model_name='task',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='task_videos/'),
        ),
    ]
