# Generated by Django 5.2.4 on 2025-09-20 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0005_alter_task_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='allow_resubmitting_task',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='task',
            name='enable_context_menu_for_students',
            field=models.BooleanField(default=True),
        ),
    ]
