# Generated by Django 5.2.4 on 2025-09-26 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0006_task_allow_resubmitting_task_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'base_manager_name': 'objects', 'verbose_name': 'Task', 'verbose_name_plural': 'Tasks'},
        ),
    ]
