# Generated by Django 5.2.4 on 2025-09-02 09:59

import django.db.models.deletion
import src.apps.common.utils.files.files
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assignments', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('file', models.FileField(blank=True, null=True, upload_to=src.apps.common.utils.files.files.unique_file_path)),
            ],
            options={
                'verbose_name': 'Answer File',
                'verbose_name_plural': 'Answer Files',
                'db_table': 'Answer Files',
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('in_review', 'In review'), ('approved', 'Approved'), ('have_flaws', 'Have Flaws'), ('rejected', 'Rejected')], default='in_review', max_length=20)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='assignments.task')),
            ],
            options={
                'verbose_name': 'Answer',
                'verbose_name_plural': 'Answers',
                'db_table': 'Answers',
            },
        ),
    ]
