# Generated by Django 5.2.4 on 2025-09-02 09:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('submissions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='answerfile',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='submissions.answer'),
        ),
        migrations.AddIndex(
            model_name='answer',
            index=models.Index(fields=['user', 'status'], name='Answers_user_id_b2e564_idx'),
        ),
        migrations.AddIndex(
            model_name='answer',
            index=models.Index(fields=['task', 'status'], name='Answers_task_id_6df16e_idx'),
        ),
        migrations.AddIndex(
            model_name='answer',
            index=models.Index(fields=['status', 'created_at'], name='Answers_status_91525d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together={('user', 'task')},
        ),
    ]
