# Generated by Django 5.2.4 on 2025-09-26 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answerfile',
            options={},
        ),
        migrations.AddField(
            model_name='answerfile',
            name='content_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='answerfile',
            name='original_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='answerfile',
            name='size',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterModelTable(
            name='answerfile',
            table=None,
        ),
    ]
