# Generated by Django 5.2.4 on 2025-09-02 09:59

import django.core.validators
import django.db.models.deletion
import src.apps.common.utils.files.images
import src.apps.common.utils.validators
import src.apps.common.validators.validate_weekdays
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to=src.apps.common.utils.files.images.unique_image_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png']), src.apps.common.utils.validators.validate_image_size])),
                ('deadline_to_finish_course', models.DateTimeField(blank=True, null=True, verbose_name='Deadline to finish course')),
                ('block_course_after_deadline', models.BooleanField(default=False)),
                ('is_certificated', models.BooleanField(default=True)),
                ('free_order', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'db_table': 'Courses',
            },
        ),
        migrations.CreateModel(
            name='CourseEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('student', 'Student'), ('assistant', 'Assistant'), ('teacher', 'Teacher')], default='student', max_length=20)),
                ('enrolled_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Course Enrollment',
                'verbose_name_plural': 'Course Enrollments',
                'db_table': 'Course Enrollments',
            },
        ),
        migrations.CreateModel(
            name='CourseGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=100)),
                ('students_limit', models.PositiveIntegerField(blank=True, null=True)),
                ('days_of_week', models.JSONField(blank=True, default=list, help_text='List of weekday numbers (0=Monday)', validators=[src.apps.common.validators.validate_weekdays.validate_days_of_week])),
                ('self_registration', models.BooleanField(default=False)),
                ('registration_token', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('token_validity_hours', models.PositiveIntegerField(blank=True, help_text='Number of hours the registration token should be valid. Leave empty for no expiration.', null=True)),
                ('token_validity_days', models.PositiveIntegerField(blank=True, help_text='Number of days the registration token should be valid. Leave empty for no expiration.', null=True)),
            ],
            options={
                'verbose_name': 'Course Group',
                'verbose_name_plural': 'Course Groups',
                'db_table': 'Course Groups',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=100)),
                ('parent_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='courses.category')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'db_table': 'Categories',
            },
        ),
    ]
