# Generated by Django 5.2.4 on 2025-09-02 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursegroup',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
