# Generated by Django 5.2.4 on 2025-09-02 20:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_coursegroup_is_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='coursegroup',
            name='teachers',
            field=models.ManyToManyField(blank=True, related_name='m2m_teacher_groups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='coursegroup',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_groups', to=settings.AUTH_USER_MODEL),
        ),
    ]
