# Generated by Django 5.2.4 on 2025-09-02 20:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_coursegroup_teachers_alter_coursegroup_teacher'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='courseenrollment',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='coursegroup',
            name='teachers',
        ),
        migrations.AddConstraint(
            model_name='courseenrollment',
            constraint=models.UniqueConstraint(condition=models.Q(('role', 'student')), fields=('user', 'course'), name='uniq_student_per_course'),
        ),
        migrations.AddConstraint(
            model_name='courseenrollment',
            constraint=models.UniqueConstraint(fields=('user', 'group', 'role'), name='uniq_user_group_role'),
        ),
    ]
