# Generated by Django 5.2.4 on 2025-09-19 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_courseenrollment_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='allow_teachers_to_manage_tasks',
            field=models.BooleanField(default=False),
        ),
    ]
