# Generated by Django 5.2.4 on 2025-09-26 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_course_allow_teachers_to_manage_tasks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursegroup',
            name='teacher',
        ),
    ]
