# Generated by Django 5.2.4 on 2025-09-26 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='feedback_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
